[build]
  publish = "."  # Este é o diretório correto que contém seus arquivos
  functions = "netlify/functions"  # Mantenha se você for usar funções no Netlify

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
