[build]
  publish = "static"   # Pasta onde o Netlify vai procurar os arquivos públicos
  functions = "functions"  # Diretório onde as funções são armazenadas, se houver

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

