[build]
publish = "static"  # Alterando para a pasta que contém os arquivos estáticos
command = "python app.py"  # Mantendo o comando para rodar o servidor Flask

[[plugins]]
package = "@netlify/plugin-functions-install-core"
